- name: Update and Upgrade
  ansible.builtin.cron:
    name: "update and upgrade"
    minute: "0"
    hour: "00"
    job: "apt update && apt upgrade"
    user: "root"
  become: true

- name: remove rae user's cron job
  ansible.builtin.cron:
    name: "update and upgrade"
    state: absent

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: ~/test
    state: touch
    owner: rae
    group: rae
    mode: '0644'