- name: Update and Upgrade
  ansible.builtin.cron:
    name: "update and upgrade"
    minute: "0"
    hour: "00"
    job: "apt update && apt upgrade"
    user: "root"
  become: true

- name: Create ansible cron log file
  ansible.builtin.file:
    path: /var/log/rae_connect_asnible.log
    state: touch
    owner: rae
    group: rae
    mode: '0644'
  become: true

- name: Ansible Update
  ansible.builtin.cron:
    name: "Ansible Update"
    minute: "0"
    hour: "3"
    job: "/home/rae/.local/bin/ansible-pull -U git@github.com:rae-corporation/RAEConnectAnsible.git -C main site.yml -i hosts >> /var/log/rae_connect_asnible.log 2>&1"

- name: Install dotnet SDK
  ansible.builtin.apt:
    name: dotnet-sdk-6.0
    update_cache: yes
  become: true

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /src/RAEConnect
    state: directory
    owner: rae
    group: rae
    mode: '0755'
  become: true

- name: Git checkout RAEConnectServer
  ansible.builtin.git:
    repo: 'git@github.com:rae-corporation/RAEConnectServer.git'
    dest: /src/RAEConnect
  register: gitResult

- name: Create application directory
  ansible.builtin.file:
    path: /RAEConnect
    state: directory
    owner: rae
    group: rae
    mode: '0755'
  become: true

- name: Deploy RAE Connect
  ansible.builtin.shell: dotnet publish /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
  args:
    chdir: /src/RAEConnect
  when: gitResult.before != gitResult.after

