- name: Update and Upgrade
  ansible.builtin.cron:
    name: "update and upgrade"
    minute: "0"
    hour: "00"
    job: "apt update && apt upgrade"
    user: "root"
    state: absent
  become: true

- name: Create ansible cron log file
  ansible.builtin.file:
    path: /var/log/rae_connect_asnible.log
    state: touch
    owner: rae
    group: rae
    mode: '0644'
  become: true

- name: Ansible Update
  ansible.builtin.cron:
    name: "Ansible Update"
    minute: "*/5"
    hour: "*"
    job: "ansible-pull -U https://github.com/rae-corporation/RAEConnectAnsible.git -C test site.yml >> /var/log/rae_connect_asnible.log 2>&1"

- name: Install dotnet SDK
  ansible.builtin.apt:
    name: dotnet-sdk-6.0
    update_cache: yes
  become: true

- name: Install dotnet 9
  ansible.builtin.apt:
    name: aspnetcore-runtime-9.0
    update_cache: yes
  become: true
   
- name: Copy DashboardUpdate.sh
  ansible.builtin.copy:
    src: ./DashboardUpdate.sh
    dest: /ConnectDashboard/update
  become: true

- name: Install isc-kea
  ansible.builtin.apt:
    name: kea
    update_cache: yes
  become: true

- name: Copy kea-dhcp4.conf
  ansible.builtin.copy:
    src: ./kea-dhcp4.conf
    dest: /etc/kea/kea-dhcp4.conf
  become: true

- name: Check for string with grep
  shell: cat /etc/dhcp/dhclient.conf | grep -E "^[^#].*dhcp-client-identifier = hardware"
  register: grep_result
  ignore_errors: yes
  failed_when: grep_result.rc != 0 and grep_result.rc != 1
  
- name: Task if string found via grep
  shell: echo send dhcp-client-identifier = hardware\; >> /etc/dhcp/dhclient.conf
  when: grep_result.rc == 1

- name: Restart DHCP if dhclient.conf updated
  shell: dhclient -r && dhclient
  when: grep_result.rc == 1

# - name: Copy RAEConnect systemd service file
#   ansible.builtin.copy:
#     src: ./RAEConnect.service
#     dest: /etc/systemd/system/
#   become: true


# - name: Copy SSH config file
#   ansible.builtin.copy:
#     src: ./ssh_config
#     dest: /etc/ssh/
#   become: true

- name: Force systemd to reread configs
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart DHCP
  ansible.builtin.systemd:
    service: kea-dhcp4-server.service
    state: "started"
  become: true
