- name: Update and Upgrade
  ansible.builtin.cron:
    name: "update and upgrade"
    minute: "0"
    hour: "00"
    job: "apt update && apt upgrade"
    user: "root"
  become: true

- name: 'Ensure an old job is no longer present. Removes any job that is prefixed by "#Ansible: an old job" from the crontab'
  ansible.builtin.cron:
    name: "Update and Upgrade"
    state: absent

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: ~/test
    state: touch
    owner: rae
    group: rae
    mode: '0644'