- name: Update and Upgrade
  ansible.builtin.cron:
    name: "update and upgrade"
    minute: "0"
    hour: "00"
    job: "apt update && apt upgrade"
    user: "root"
    state: absent
  become: true

- name: Create ansible cron log file
  ansible.builtin.file:
    path: /var/log/rae_connect_asnible.log
    state: touch
    owner: rae
    group: rae
    mode: '0644'
  become: true

- name: Ansible Update
  ansible.builtin.cron:
    name: "Ansible Update"
    minute: "0"
    hour: "*"
    job: "/home/rae/.local/bin/ansible-pull -U git@github.com:rae-corporation/RAEConnectAnsible.git -C main site.yml -i hosts >> /var/log/rae_connect_asnible.log 2>&1"

- name: Install dotnet SDK
  ansible.builtin.apt:
    name: dotnet-sdk-6.0
    update_cache: yes
  become: true

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /src/RAEConnect
    state: directory
    owner: rae
    group: rae
    mode: '0755'
  become: true

- name: Git checkout RAEConnectServer
  ansible.builtin.git:
    repo: 'git@github.com:rae-corporation/RAEConnectServer.git'
    dest: /src/RAEConnect
  register: gitResult

- name: Create application directory
  ansible.builtin.file:
    path: /RAEConnect
    state: directory
    owner: rae
    group: rae
    mode: '0755'
  become: true

   
- name: Check RAEConnect Server executable exists 
  stat:
    path: /RAEConnect/RAEConnectServer
  register: exe_stat

- name: Deploy RAE Connect
  ansible.builtin.shell: dotnet publish /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
  args:
    chdir: /src/RAEConnect
  when: gitResult.before != gitResult.after or not exe_stat.stat.exists



- name: Copy RAEConnect systemd service file
  ansible.builtin.copy:
    src: ./RAEConnect.service
    dest: /etc/systemd/system/
  become: true

- name: Force systemd to reread configs
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Create logging directory
  ansible.builtin.file:
    path: /var/log/RAEConnect
    state: directory
    owner: rae
    group: rae
    mode: '0755'
  become: true

- name: Start and enable RAEConnect Server
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: RAEConnect
  become: true


- name: Set IP of eth4 at boot
  ansible.builtin.cron:
    name: "Set IP of eth4 at boot"
    special_time: reboot
    job: "/usr/sbin/ip addr add 172.16.255.254/16 dev eno4"
  become: true